[versions]
minecraft = "1.21.5"
parchment = "2025.06.15"

fabric-api = "0.127.1+1.21.5"

resourceful-lib = "3.5.0"
resourceful-config = "3.5.16"

olympus = "1.3.6"
placeholders = "2.6.4+1.21.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.21.5", version.ref = "parchment" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version.ref = "resourceful-lib" }
resourceful-config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.5", version.ref = "resourceful-config" }

olympus = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version.ref = "olympus" }
placeholders = { module = "eu.pb4:placeholder-api", version.ref = "placeholders" }
