[versions]

# Minecraft
minecraft = "1.21.5"
loom = "1.10-SNAPSHOT"
loader = "0.16.10"

# Dependencies
fabric = "0.119.5+1.21.5"
fabrickotlin = "1.13.0+kotlin.2.1.0"
skyblockapi = "1.0.0-beta.86"
hypixelapi = "1.0.1+build.1+mc1.21"
rconfig = "3.5.2"
rconfigkt = "3.5.4"
olympus = "1.3.0"
rlib = "3.5.0"
discordipc = "0.5.3"

# Dev Dependencies
devauth = "1.2.1"
modmenu = "14.0.0-rc.2"

[libraries]

minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
fabric = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }
fabrickotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabrickotlin" }
skyblockapi = { module = "tech.thatgravyboat:skyblock-api-1.21.5", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }
rconfig = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.5", version.ref = "rconfig" }
rconfigkt = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }
olympus = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version.ref = "olympus" }
rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version.ref = "rlib" }
discordipc = { module = "com.jagrosh:DiscordIPC", version.ref = "discordipc" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]

loom = { id = "fabric-loom", version.ref = "loom" }