[versions]

fabric-loader = "0.18.2"
fabric-language-kotlin = "1.13.4+kotlin.2.2.0"

kotlin-symbol-processor = "2.2.0-2.0.2"

# Dependencies
skyblockapi = "4.0.8"
hypixelapi = "1.0.1+build.1+mc1.21"

rconfigkt = "3.5.12"

meowdding-lib = "4.0.6"

discordipc = "0.6.6"

[libraries]

fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

skyblockapi = { module = "tech.thatgravyboat:skyblock-api", version.ref = "skyblockapi" }
hypixelapi = { module = "maven.modrinth:hypixel-mod-api", version.ref = "hypixelapi" }

resourcefulkt-config = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-fabric-1.21.5", version.ref = "rconfigkt" }

meowdding-lib = { module = "me.owdding.meowdding-lib:meowdding-lib", version.ref = "meowdding-lib" }

discordipc = { module = "io.github.vyfor:kpresence", version.ref = "discordipc" }

[plugins]
kotlin-symbol-processor = { id = "com.google.devtools.ksp", version.ref = "kotlin-symbol-processor" }
